/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.sampleapps.web.wavecalendar.eventdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class UsereventsResponse implements Serializable {

    @JsonProperty("URL")
    @ColumnAlias("URL")
    private String url;
    @JsonProperty("allDay")
    @ColumnAlias("allDay")
    private Boolean allDay;
    @JsonProperty("color")
    @ColumnAlias("color")
    private String color;
    @JsonProperty("description")
    @ColumnAlias("description")
    private String description;
    @JsonProperty("end")
    @ColumnAlias("end")
    private Timestamp end;
    @JsonProperty("id")
    @ColumnAlias("id")
    private Integer id;
    @JsonProperty("start")
    @ColumnAlias("start")
    private Timestamp start;
    @JsonProperty("title")
    @ColumnAlias("title")
    private String title;

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Boolean getAllDay() {
        return this.allDay;
    }

    public void setAllDay(Boolean allDay) {
        this.allDay = allDay;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getEnd() {
        return this.end;
    }

    public void setEnd(Timestamp end) {
        this.end = end;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Timestamp getStart() {
        return this.start;
    }

    public void setStart(Timestamp start) {
        this.start = start;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UsereventsResponse)) return false;
        final UsereventsResponse usereventsResponse = (UsereventsResponse) o;
        return Objects.equals(getUrl(), usereventsResponse.getUrl()) &&
                Objects.equals(getAllDay(), usereventsResponse.getAllDay()) &&
                Objects.equals(getColor(), usereventsResponse.getColor()) &&
                Objects.equals(getDescription(), usereventsResponse.getDescription()) &&
                Objects.equals(getEnd(), usereventsResponse.getEnd()) &&
                Objects.equals(getId(), usereventsResponse.getId()) &&
                Objects.equals(getStart(), usereventsResponse.getStart()) &&
                Objects.equals(getTitle(), usereventsResponse.getTitle());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUrl(),
                getAllDay(),
                getColor(),
                getDescription(),
                getEnd(),
                getId(),
                getStart(),
                getTitle());
    }
}
